-- LangBlue / Supabase server layer
-- Local-first: only social-access state and comments are stored here.
create table if not exists public.foreign_access (
  local_user_id text primary key,
  share_started boolean not null default false,
  share_completed boolean not null default false,
  share_platform text,
  share_at timestamptz,
  comment_completed boolean not null default false,
  completed_at timestamptz,
  updated_at timestamptz not null default now()
);
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  local_user_id text not null,
  comment text not null check (char_length(comment) between 5 and 1000),
  created_at timestamptz not null default now()
);
create index if not exists comments_local_user_id_idx on public.comments(local_user_id);
alter table public.foreign_access enable row level security;
alter table public.comments enable row level security;
drop policy if exists "LangBlue foreign access select" on public.foreign_access;
drop policy if exists "LangBlue foreign access insert" on public.foreign_access;
drop policy if exists "LangBlue foreign access update" on public.foreign_access;
create policy "LangBlue foreign access select" on public.foreign_access for select to anon, authenticated using (true);
create policy "LangBlue foreign access insert" on public.foreign_access for insert to anon, authenticated with check (true);
create policy "LangBlue foreign access update" on public.foreign_access for update to anon, authenticated using (true) with check (true);
drop policy if exists "LangBlue comments select" on public.comments;
drop policy if exists "LangBlue comments insert" on public.comments;
create policy "LangBlue comments select" on public.comments for select to anon, authenticated using (true);
create policy "LangBlue comments insert" on public.comments for insert to anon, authenticated with check (char_length(comment) between 5 and 1000);
grant select, insert, update on public.foreign_access to anon, authenticated;
grant select, insert on public.comments to anon, authenticated;
