import "jsr:@supabase/functions-js/edge-runtime.d.ts";import{createClient}from"jsr:@supabase/supabase-js@2";
const O="https://lngbl.github.io",L=["A1","A2","B1","B2","C1","C2"],J=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{"Access-Control-Allow-Origin":O,"Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST,OPTIONS","Content-Type":"application/json","Cache-Control":"no-store"}}),S=<T>(a:T[])=>{a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
Deno.serve(async r=>{if(r.method==="OPTIONS")return new Response(null,{status:204,headers:{"Access-Control-Allow-Origin":O,"Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST,OPTIONS","Access-Control-Max-Age":"86400"}});if(r.method!=="POST"||r.headers.get("Origin")!==O)return J({ok:false,error:"REQUEST_NOT_ALLOWED"},403);const u=Deno.env.get("SUPABASE_URL"),k=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),a=Deno.env.get("SUPABASE_ANON_KEY");if(!u||!k||!a)return J({ok:false,error:"CONFIG"},500);const t=(r.headers.get("Authorization")||"").replace(/^Bearer\s+/i,"");if(!t)return J({ok:false,error:"AUTH_REQUIRED"},401);const ac=createClient(u,a,{auth:{persistSession:false,autoRefreshToken:false}}),au=await ac.auth.getUser(t);if(au.error||!au.data.user)return J({ok:false,error:"AUTH_REQUIRED"},401);const db=createClient(u,k,{auth:{persistSession:false,autoRefreshToken:false}});let b:any={};try{b=await r.json()}catch{return J({ok:false,error:"INVALID_JSON"},400)}const act=String(b.action||"bootstrap");
if(act==="bootstrap"){const p=await db.from("profiles").select("arabic_level").eq("id",au.data.user.id).maybeSingle();const lv=L.includes(b.level)?b.level:(p.data?.arabic_level||"A1"),q=await db.from("question_pool").select("id,level,source_type,source_content,translation_fa,word_type,grammar_explanation_fa,example_text").eq("language","arabic").eq("level",lv).eq("active",true);if(q.error)return J({ok:false,error:"CONTENT_LOAD"},500);return J({ok:true,level:lv,vocabulary:(q.data||[]).filter(x=>x.source_type==="vocabulary"),grammar:(q.data||[]).filter(x=>x.source_type==="grammar")})}
if(act==="set_level"){if(!L.includes(b.level))return J({ok:false,error:"INVALID_LEVEL"},400);const x=await db.from("profiles").update({arabic_level:b.level,updated_at:new Date().toISOString()}).eq("id",au.data.user.id);return x.error?J({ok:false,error:"LEVEL_SAVE"},500):J({ok:true,level:b.level})}
if(act==="placement_start"){const old=await db.from("arabic_assessment_sessions").select("id").eq("user_id",au.data.user.id).eq("status","active").maybeSingle();if(old.data)return J({ok:false,error:"ASSESSMENT_ACTIVE"},409);const p=await db.from("question_pool").select("id,level,source_type,source_content,translation_fa,example_text").eq("language","arabic").eq("active",true);if(p.error)return J({ok:false,error:"POOL_LOAD"},500);let qs:any[]=[];for(const lv of L){const z=S((p.data||[]).filter(x=>x.level===lv));qs.push(...z.filter(x=>x.source_type==="vocabulary").slice(0,2),...z.filter(x=>x.source_type==="grammar").slice(0,1))}qs=qs.slice(0,18);if(qs.length<12)return J({ok:false,error:"POOL_SMALL"},503);const snap=qs.map(q=>{const ds=S((p.data||[]).filter(x=>x.id!==q.id&&x.source_type===q.source_type&&x.translation_fa!==q.translation_fa)).slice(0,3).map(x=>x.translation_fa);const op=S([q.translation_fa,...ds]);return{id:q.id,level:q.level,source_type:q.source_type,prompt:q.source_content,example_text:q.example_text||null,options:op,correct_index:op.indexOf(q.translation_fa)}});const id=crypto.randomUUID(),x=await db.from("arabic_assessment_sessions").insert({id,user_id:au.data.user.id,level_snapshot:"A1",question_ids:snap.map(x=>x.id),question_snapshot:snap,answers:[],status:"active"});if(x.error)return J({ok:false,error:"SESSION_CREATE"},500);return J({ok:true,session_id:id,questions:snap.map(({correct_index,...x})=>x),question_count:snap.length})}
if(act==="placement_submit"){const id=String(b.session_id||""),ans=Array.isArray(b.answers)?b.answers:[],s=await db.from("arabic_assessment_sessions").select("*").eq("id",id).eq("user_id",au.data.user.id).eq("status","active").maybeSingle();if(s.error||!s.data)return J({ok:false,error:"SESSION_NOT_FOUND"},404);const map=new Map((s.data.question_snapshot||[]).map((q:any)=>[q.id,q]));let score=0;const lev:any={};const out:any[]=[];for(const a of ans){const q=map.get(String(a.question_id));if(!q)continue;const ok=Number(a.selected_index)===q.correct_index;if(ok)score++;lev[q.level]??={correct:0,total:0};lev[q.level].total++;if(ok)lev[q.level].correct++;out.push({question_id:q.id,selected_index:Number(a.selected_index),correct:ok})}let d="A1";for(const x of L){if(lev[x]&&lev[x].correct/lev[x].total>=.67)d=x}const pct=Math.round(score/Math.max(1,map.size)*10000)/100;await db.from("arabic_assessment_sessions").update({answers:out,score,percent:pct,detected_level:d,status:"completed",completed_at:new Date().toISOString()}).eq("id",id);await db.from("profiles").update({arabic_level:d,updated_at:new Date().toISOString()}).eq("id",au.data.user.id);await db.from("behavior_events").insert([{event_id:crypto.randomUUID(),user_id:au.data.user.id,event_name:"assessment_completed",product_id:"arabic",language:"arabic",context_id:"arabic_placement",event_payload:{session_id:id,score,percent:pct,detected_level:d,by_level:lev},occurred_at:new Date().toISOString(),schema_version:1,source:"arabic-assessment"}]);return J({ok:true,score,percent:pct,detected_level:d,by_level:lev})}
if(act==="contribute"){
 const p=await db.from("profiles").select("peer_learning_consent,exam_contribution_consent").eq("id",au.data.user.id).maybeSingle();
 if(p.error)return J({ok:false,error:"PROFILE_LOAD"},500);
 if(!p.data?.peer_learning_consent)return J({ok:true,accepted:0,skipped:"CONSENT_REQUIRED"});
 const items=Array.isArray(b.items)?b.items.slice(0,200):[];
 if(!items.length)return J({ok:true,accepted:0});
 const rows=[];
 for(const raw of items){
  const source_type=raw?.source_type==="grammar"?"grammar":"vocabulary";
  const source_content=String(raw?.source_content||"").trim();
  if(!source_content)continue;
  const payload={source_type,source_content,translation_fa:String(raw?.translation_fa||""),word_type:String(raw?.word_type||""),grammar_explanation_fa:String(raw?.grammar_explanation_fa||""),example_text:String(raw?.example_text||"")};
  const canonical=JSON.stringify({language:"arabic",level:String(b.level||"A1"),...payload});
  const hashBuf=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(canonical));
  const source_hash=Array.from(new Uint8Array(hashBuf)).map(x=>x.toString(16).padStart(2,"0")).join("");
  rows.push({user_id:au.data.user.id,source_type,language:"arabic",language_level:String(b.level||"A1"),payload,source_hash,consent_snapshot:true,exam_eligible:p.data.exam_contribution_consent===true});
 }
 if(!rows.length)return J({ok:true,accepted:0});
 const hashes=rows.map(x=>x.source_hash);
 const ex=await db.from("content_contributions").select("source_hash").eq("user_id",au.data.user.id).in("source_hash",hashes);
 if(ex.error)return J({ok:false,error:"CONTRIBUTION_LOOKUP"},500);
 const seen=new Set((ex.data||[]).map(x=>x.source_hash));
 const fresh=rows.filter(x=>!seen.has(x.source_hash));
 if(fresh.length){
  const ins=await db.from("content_contributions").insert(fresh);
  if(ins.error)return J({ok:false,error:"CONTRIBUTION_SAVE"},500);
 }
 return J({ok:true,accepted:fresh.length,skipped:rows.length-fresh.length});
}return J({ok:false,error:"UNKNOWN_ACTION"},400)});